import { describe,expect,it } from "vitest";
import { currentQuarter,quarterFromDate,qualifyingProjects,sanitizePlainText,shiftQuarter,sortProjectsByPriority,visibleInitiatives,visibleProjectMilestones,visibleProjectsForBoard } from "@/lib/roadmap";
import { demoSnapshot } from "@/lib/demo-data";
import { cleanProjectUpdate,sheetDate,sheetHealth,sheetMilestones,statusUpdateAuthor } from "@/lib/google-sheets";

describe("roadmap conventions",()=>{
  it("derives quarter boundaries",()=>{expect(quarterFromDate("2026-01-01")).toBe("Q1 2026");expect(quarterFromDate("2026-03-31")).toBe("Q1 2026");expect(quarterFromDate("2026-04-01")).toBe("Q2 2026");expect(quarterFromDate("2026-12-31")).toBe("Q4 2026")});
  it("moves across year boundaries",()=>{expect(shiftQuarter("Q4 2026",1)).toBe("Q1 2027");expect(shiftQuarter("Q1 2026",-1)).toBe("Q4 2025")});
  it("uses the configured timezone for current quarter",()=>{expect(currentQuarter(new Date("2026-08-05T12:00:00Z"))).toBe("Q3 2026")});
  it("excludes canceled initiatives",()=>{const canceled={...demoSnapshot.initiatives[0],id:"x",status:"Canceled"};expect(visibleInitiatives([...demoSnapshot.initiatives,canceled],"Q3 2026").some((x)=>x.id==="x")).toBe(false)});
  it("includes Product-owned and visible-goal-linked work",()=>{const visible=new Set(["migrate"]);const projects=qualifyingProjects(demoSnapshot.projects,visible);expect(projects.some((p)=>p.id==="payments")).toBe(true);expect(projects.some((p)=>p.id==="notifications")).toBe(true)});
  it("strips markdown and links from executive text",()=>{expect(sanitizePlainText("**Hello** [team](https://example.com) <script>x</script>")).toBe("Hello team x")});
  it("maps exclusive sheet quarter boundaries",()=>{expect(sheetDate("10/1/2026",true)).toBe("2026-09-30")});
  it("maps sheet health values",()=>{expect(sheetHealth("At risk")).toBe("atRisk");expect(sheetHealth("No updates")).toBeNull()});
  it("maps exported milestones",()=>{expect(sheetMilestones("p1","Beta[next],GA[unstarted],Shaping[done](Target Date: 2026-08-07)")).toEqual([{id:"p1-milestone-0",name:"Beta",description:null,targetDate:null},{id:"p1-milestone-1",name:"GA",description:null,targetDate:null},{id:"p1-milestone-2",name:"Shaping",description:null,targetDate:"2026-08-07"}])});
  it("uses exact Linear statuses and a six-month maintenance window",()=>{const base=demoSnapshot.projects[0];const projects=[{...base,id:"ready",status:"Ready",teamNames:["Product"]},{...base,id:"framing",status:"Framing",teamNames:["Product"]},{...base,id:"other",status:"Building",teamNames:["Engineering"]},{...base,id:"recent",status:"Maintenance",teamNames:["Product"],targetDate:"2026-02-06"},{...base,id:"old",status:"Maintenance",teamNames:["Product"],targetDate:"2026-02-05"},{...base,id:"undated",status:"Maintenance",teamNames:["Product"],targetDate:null}];expect(visibleProjectsForBoard(projects,new Date("2026-08-06T12:00:00Z")).map((project)=>project.id)).toEqual(["ready","recent"])});
  it("keeps only the narrative portion of exported project updates",()=>{const update="🟢 On track | Brayan Acebo posted an update on Jul 29\nThe build is complete and ready for rollout.\n\n**Status**: Build Complete **Target date**: Jul 5th → Jul 26th\n*Progress since Jul 6*: — **QA**: 96% → 100%";expect(cleanProjectUpdate(update)).toBe("The build is complete and ready for rollout.")});
  it("extracts the author from an exported status update",()=>{expect(statusUpdateAuthor("🟢 On track | Brayan Acebo posted an update on Jul 29\nShipped.")).toBe("Brayan Acebo");expect(statusUpdateAuthor("Shipped.")).toBeNull()});
  it("filters and orders project milestones",()=>{const milestones=[{id:"feedback",name:"Feedback",description:null,targetDate:"2026-07-01"},{id:"beta",name:"Beta",description:null,targetDate:null},{id:"internal",name:"Internal",description:null,targetDate:null},{id:"dated-late",name:"GA",description:null,targetDate:"2026-09-01"},{id:"shaping",name:"Shaping",description:null,targetDate:null},{id:"dated-early",name:"Alpha",description:null,targetDate:"2026-08-01"},{id:"building",name:"Building",description:null,targetDate:null}];expect(visibleProjectMilestones(milestones).map((milestone)=>milestone.id)).toEqual(["dated-early","dated-late","shaping","building","internal","beta"])});
  it("orders projects by Linear priority within a status",()=>{const base=demoSnapshot.projects[0];const projects=[{...base,id:"none",priority:"No priority"},{...base,id:"medium",priority:"Medium"},{...base,id:"urgent",priority:"Urgent"},{...base,id:"low",priority:"Low"},{...base,id:"high",priority:"High"}];expect(sortProjectsByPriority(projects).map((project)=>project.id)).toEqual(["urgent","high","medium","low","none"])});
});
