import type { RoadmapSnapshot } from "@/lib/types";

export const demoSnapshot: RoadmapSnapshot = {
  source: "preview", syncedAt: "2026-08-05T14:42:00.000Z",
  initiatives: [
    { id:"migrate", name:"Migrate to PleiOS", summary:"Migrate 100% of organizers and internal teams off legacy systems", status:"Active", health:"onTrack", owner:"Stefano Sanchez", targetDate:"2026-09-30", latestUpdate:"Core game and member management are complete. The team is now closing the remaining organizer workflows and preparing staged rollouts.", latestUpdateAt:"2026-08-04T18:30:00.000Z" },
    { id:"orbit", name:"Increase Orbit usage", summary:"Increase weekly Orbit usage to 80% of eligible users", status:"Active", health:"atRisk", owner:"Stefano Sanchez", targetDate:"2026-09-30", latestUpdate:"Adoption is growing, but repeat usage is behind target. The next release focuses on faster answers and clearer suggested prompts.", latestUpdateAt:"2026-08-02T16:00:00.000Z" },
    { id:"video", name:"Video recording validation", summary:"Validate a go / no-go decision for integrating video recording", status:"Active", health:null, owner:"Stefano Sanchez", targetDate:"2026-09-30", latestUpdate:null, latestUpdateAt:null },
    { id:"retention", name:"Increase weekly retention", summary:"Increase weekly player return rate by 5%", status:"Planned", health:null, owner:"Stefano Sanchez", targetDate:"2026-12-31", latestUpdate:null, latestUpdateAt:null },
  ],
  projects: [
    { id:"notifications", name:"Game notifications", summary:"Migrate organizer SMS notifications to PleiOS", status:"Shaping", statusType:"planned", health:"onTrack", lead:"Tomas Noseda", startDate:"2026-08-03", targetDate:"2026-09-12", initiativeIds:["migrate"], teamNames:["Product"], latestUpdate:"Scope validated with active organizers; shaping the notification controls and delivery rules.", latestUpdateAt:"2026-08-03T19:03:00.000Z", milestones:[{id:"n1",name:"Internal pilot",description:null,targetDate:"2026-08-24"},{id:"n2",name:"Organizer beta",description:null,targetDate:"2026-09-02"},{id:"n3",name:"General rollout",description:null,targetDate:"2026-09-12"}] },
    { id:"banner", name:"Banner management", summary:"Rebuild banner management for business teams in PleiOS", status:"Ready", statusType:"planned", health:null, lead:"Adrian Rodriguez", startDate:"2026-08-10", targetDate:"2026-09-18", initiativeIds:["migrate"], teamNames:["Product","Engineering"], latestUpdate:"Requirements are complete and the project is ready for engineering.", latestUpdateAt:"2026-07-31T13:00:00.000Z", milestones:[{id:"b1",name:"Business-team preview",description:null,targetDate:"2026-09-04"},{id:"b2",name:"Legacy replacement",description:null,targetDate:"2026-09-18"}] },
    { id:"orbit2", name:"Orbit recommendations", summary:"Help teammates discover valuable questions and return to Orbit each week", status:"In Progress", statusType:"started", health:"atRisk", lead:"Stefano Sanchez", startDate:"2026-07-20", targetDate:"2026-08-28", initiativeIds:["orbit"], teamNames:["Product","Data"], latestUpdate:"The first recommendation set is live internally; relevance tuning remains before company rollout.", latestUpdateAt:"2026-08-04T20:10:00.000Z", milestones:[{id:"o1",name:"Internal dogfood",description:null,targetDate:"2026-08-08"},{id:"o2",name:"Company rollout",description:null,targetDate:"2026-08-28"}] },
    { id:"discovery", name:"Video recording discovery", summary:"Test player and organizer demand before committing to an integration", status:"Framing", statusType:"backlog", health:null, lead:"Stefano Sanchez", startDate:null, targetDate:null, initiativeIds:["video"], teamNames:["Product"], latestUpdate:null, latestUpdateAt:null, milestones:[] },
    { id:"payments", name:"Improving payments", summary:null, status:"Framing", statusType:"backlog", health:null, lead:null, startDate:null, targetDate:null, initiativeIds:[], teamNames:["Product"], latestUpdate:null, latestUpdateAt:null, milestones:[] },
  ],
};
