import type { RoadmapSnapshot } from "@/lib/types";

export const demoSnapshot: RoadmapSnapshot = {
  source: "preview", syncedAt: "2026-08-05T14:42:00.000Z",
  initiatives: [
    { id:"migrate", name:"Migrate to PleiOS", summary:"Move organizers and internal teams off legacy systems", status:"Active", health:"onTrack", owner:"Stefano Sanchez", targetDate:"2026-09-30", latestUpdate:"Core game and member management are complete. The team is now closing the remaining organizer workflows and preparing staged rollouts.", latestUpdateAt:"2026-08-04T18:30:00.000Z", statusUpdates:[{id:"mu1",body:"Core game and member management are complete. The team is now closing the remaining organizer workflows and preparing staged rollouts.",createdAt:"2026-08-04T18:30:00.000Z",health:"onTrack"},{id:"mu2",body:"The migration sequence is agreed and the first internal workflows are moving to PleiOS.",createdAt:"2026-07-21T15:00:00.000Z",health:"onTrack"}] },
    { id:"orbit", name:"Increase Orbit usage", summary:"Make Orbit a dependable part of weekly decision-making", status:"Active", health:"atRisk", owner:"Stefano Sanchez", targetDate:"2026-09-30", latestUpdate:"Adoption is growing, but repeat usage is behind target. The next release focuses on faster answers and clearer suggested prompts.", latestUpdateAt:"2026-08-02T16:00:00.000Z", statusUpdates:[{id:"ou1",body:"Adoption is growing, but repeat usage is behind target. The next release focuses on faster answers and clearer suggested prompts.",createdAt:"2026-08-02T16:00:00.000Z",health:"atRisk"}] },
    { id:"video", name:"Video recording validation", summary:"Reach a go / no-go decision for integrating video recording", status:"Active", health:null, owner:"Stefano Sanchez", targetDate:"2026-09-30", latestUpdate:null, latestUpdateAt:null, statusUpdates:[] },
    { id:"retention", name:"Increase weekly retention", summary:"Help more players return to Plei each week", status:"Planned", health:null, owner:"Stefano Sanchez", targetDate:"2026-12-31", latestUpdate:null, latestUpdateAt:null, statusUpdates:[] },
  ],
  projects: [
    { id:"notifications", name:"Game notifications", summary:"Migrate organizer SMS notifications to PleiOS", status:"Shaping", statusType:"planned", health:"onTrack", lead:"Tomas Noseda", startDate:"2026-08-03", targetDate:"2026-09-12", initiativeIds:["migrate"], teamNames:["Product"], latestUpdate:"Scope validated with active organizers; shaping the notification controls and delivery rules.", latestUpdateAt:"2026-08-03T19:03:00.000Z", statusUpdates:[{id:"nu1",body:"Scope validated with active organizers; shaping the notification controls and delivery rules.",createdAt:"2026-08-03T19:03:00.000Z",health:"onTrack"},{id:"nu2",body:"Usage evidence now supports migrating the organizer notification workflow into PleiOS.",createdAt:"2026-07-26T18:00:00.000Z",health:null}], milestones:[{id:"n1",name:"Internal pilot",description:null,targetDate:"2026-08-24"},{id:"n2",name:"Organizer beta",description:null,targetDate:"2026-09-02"},{id:"n3",name:"General rollout",description:null,targetDate:"2026-09-12"}] },
    { id:"banner", name:"Banner management", summary:"Rebuild banner management for business teams in PleiOS", status:"Ready", statusType:"planned", health:null, lead:"Adrian Rodriguez", startDate:"2026-08-10", targetDate:"2026-09-18", initiativeIds:["migrate"], teamNames:["Product","Engineering"], latestUpdate:"Requirements are complete and the project is ready for engineering.", latestUpdateAt:"2026-07-31T13:00:00.000Z", statusUpdates:[{id:"bu1",body:"Requirements are complete and the project is ready for engineering.",createdAt:"2026-07-31T13:00:00.000Z",health:null}], milestones:[{id:"b1",name:"Business-team preview",description:null,targetDate:"2026-09-04"},{id:"b2",name:"Legacy replacement",description:null,targetDate:"2026-09-18"}] },
    { id:"orbit2", name:"Orbit recommendations", summary:"Help teammates discover valuable questions and return to Orbit each week", status:"In Progress", statusType:"started", health:"atRisk", lead:"Stefano Sanchez", startDate:"2026-07-20", targetDate:"2026-08-28", initiativeIds:["orbit"], teamNames:["Product","Data"], latestUpdate:"The first recommendation set is live internally; relevance tuning remains before company rollout.", latestUpdateAt:"2026-08-04T20:10:00.000Z", statusUpdates:[{id:"or1",body:"The first recommendation set is live internally; relevance tuning remains before company rollout.",createdAt:"2026-08-04T20:10:00.000Z",health:"atRisk"}], milestones:[{id:"o1",name:"Internal dogfood",description:null,targetDate:"2026-08-08"},{id:"o2",name:"Company rollout",description:null,targetDate:"2026-08-28"}] },
    { id:"discovery", name:"Video recording discovery", summary:"Test player and organizer demand before committing to an integration", status:"Framing", statusType:"backlog", health:null, lead:"Stefano Sanchez", startDate:null, targetDate:null, initiativeIds:["video"], teamNames:["Product"], latestUpdate:null, latestUpdateAt:null, statusUpdates:[], milestones:[] },
    { id:"payments", name:"Improving payments", summary:null, status:"Framing", statusType:"backlog", health:null, lead:null, startDate:null, targetDate:null, initiativeIds:[], teamNames:["Product"], latestUpdate:null, latestUpdateAt:null, statusUpdates:[], milestones:[] },
  ],
};
