import Link from "next/link";
import { ArrowLeft, CalendarDays, Flag, UserRound } from "lucide-react";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { DateText, HealthBadge, RelativeUpdate } from "@/components/status";
import { StatusFeed } from "@/components/status-feed";
import { getRoadmapSnapshot } from "@/lib/linear";

export default async function ProjectDetail({params}:{params:Promise<{id:string}>}) { const {id}=await params;const snapshot=await getRoadmapSnapshot();const p=snapshot.projects.find((item)=>item.id===id);if(!p)notFound();const goals=snapshot.initiatives.filter((g)=>p.initiativeIds.includes(g.id));return <AppShell><Link className="back" href="/projects"><ArrowLeft size={15}/>All projects</Link><header className="detail-header"><div><span className="eyebrow">Product project</span><h1>{p.name}</h1><p>{p.summary||"Executive summary not set in Linear"}</p></div><span className="status">{p.status}</span></header><div className="detail-grid"><main><section className="panel"><div className="panel-heading"><h2>Latest status update</h2><span><RelativeUpdate value={p.latestUpdateAt}/></span></div><p className={p.latestUpdate?"lead-update":"lead-update empty-copy"}>{p.latestUpdate||"No recent update from Linear"}</p></section><section className="panel panel-spaced"><h2>Status update history</h2><StatusFeed updates={p.statusUpdates}/></section><section className="panel panel-spaced"><h2>Rollout plan</h2>{p.milestones.length?<div className="timeline">{p.milestones.map((m)=><div className="milestone" key={m.id}><span className="milestone-dot"/><div><h4>{m.name}</h4><p><DateText value={m.targetDate} empty="Milestone date not set"/>{m.description?` · ${m.description}`:""}</p></div></div>)}</div>:<p className="empty-copy">No rollout milestones have been added in Linear.</p>}</section></main><aside className="panel detail-aside"><h2>Project details</h2><dl className="fact-list"><div><dt>Status</dt><dd><Flag size={13}/>{p.status}</dd></div><div><dt>Health</dt><dd><HealthBadge health={p.health}/></dd></div><div><dt>Lead</dt><dd><UserRound size={13}/>{p.lead||"Not set"}</dd></div><div><dt>Target</dt><dd><CalendarDays size={13}/><DateText value={p.targetDate}/></dd></div><div><dt>Start</dt><dd><DateText value={p.startDate}/></dd></div><div><dt>Teams</dt><dd>{p.teamNames.join(", ")||"Not set"}</dd></div></dl><div className="linked"><div className="linked-label">Supports</div>{goals.length?goals.map((g)=><Link key={g.id} className="project-row" href={`/goals/${g.id}`}><span>{g.name}</span><span className="arrow">→</span></Link>):<p className="empty-copy">No linked quarterly goal</p>}</div></aside></div></AppShell>}
