import Link from "next/link";
import { ArrowLeft, CalendarDays, Flag, UserRound } from "lucide-react";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { DateText, HealthBadge, RelativeUpdate } from "@/components/status";
import { getRoadmapSnapshot } from "@/lib/linear";
import { quarterFromDate } from "@/lib/roadmap";

export default async function ProjectDetail({params}:{params:Promise<{id:string}>}) { const {id}=await params;const snapshot=await getRoadmapSnapshot();const p=snapshot.projects.find((item)=>item.id===id);if(!p)notFound();const goals=snapshot.initiatives.filter((g)=>p.initiativeIds.includes(g.id));return <AppShell><Link className="back" href="/projects"><ArrowLeft size={15}/>All projects</Link><div className="hero" style={{paddingTop:28}}><div><span className="eyebrow">Product project</span><h1 className="detail-title">{p.name}</h1><p className={p.summary?"":"empty-copy"}>{p.summary||"Executive summary not set in Linear"}</p></div><span className="status">{p.status}</span></div><div className="detail-grid"><main><section className="panel"><h2>Latest update</h2><div className="update-label"><span>From Linear</span><span><RelativeUpdate value={p.latestUpdateAt}/></span></div><p className={p.latestUpdate?"summary":"summary empty-copy"}>{p.latestUpdate||"No recent update from Linear"}</p></section><section className="panel" style={{marginTop:22}}><h2>Rollout plan</h2>{p.milestones.length?<div className="timeline">{p.milestones.map((m)=><div className="milestone" key={m.id}><span className="milestone-dot"/><div><h4>{m.name}</h4><p><DateText value={m.targetDate} empty="Milestone date not set"/>{m.description?` · ${m.description}`:""}</p></div></div>)}</div>:<p className="empty-copy">No rollout milestones have been added in Linear.</p>}</section></main><aside className="panel"><h2>Project details</h2><div className="facts"><div className="fact"><label>Status</label><strong><Flag size={13}/> {p.status}</strong></div><div className="fact"><label>Health</label><HealthBadge health={p.health}/></div><div className="fact"><label>Lead</label><strong><UserRound size={13}/> {p.lead||<em>Not set</em>}</strong></div><div className="fact"><label>Target</label><strong><CalendarDays size={13}/> <DateText value={p.targetDate}/></strong></div><div className="fact"><label>Start</label><strong><DateText value={p.startDate}/></strong></div><div className="fact"><label>Teams</label><strong>{p.teamNames.join(", ")||<em>Not set</em>}</strong></div></div><div className="linked" style={{marginTop:28}}><div className="linked-label">Supports</div>{goals.length?goals.map((g)=><Link key={g.id} className="project-row" href={`/?quarter=${encodeURIComponent(quarterFromDate(g.targetDate)||"")}`}><span>{g.name}</span><span className="arrow">→</span></Link>):<p className="empty-copy">No linked quarterly goal</p>}</div></aside></div></AppShell>}
